CREATE TABLE tbl_images (

    IMG_FILE_SEQ NUMBER PRIMARY KEY,
    IMG_FILE_P_CODE NUMBER,
    IMG_FILE_ORIGIN_NAME nVARCHAR2(255),
    IMG_FILE_UPLOAD_NAME nVARCHAR2(255)


);

CREATE SEQUENCE SEQ_IMAGES
START WITH 1 INCREMENT BY 1;